name: 'tiamat'

services:
  db:
    container_name: '${COMPOSE_PROJECT_NAME}_postgis13'
    image: 'postgis/postgis:13-master'
    hostname: postgres
    platform: linux/amd64
    restart: always
    environment:
      POSTGRES_USER: tiamat
      POSTGRES_PASSWORD: tiamat
      POSTGRES_HOST: postgres
    ports:
      - "37432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql
    networks:
      - tiamat-net

volumes:
  postgres-data:

networks:
  tiamat-net:
