replicas: 2

deployment:
  name: tiamat

rollingUpdate:
  maxSurge: 1
  maxUnavailable: 1

resources:
  memLimit: 10000Mi
  cpuRequest: 1200m
  memRequest: 7500Mi
  xss: 1024m
  xmx: 7g

configMapMount:
   name: tiamat-config

image:
  identifier: <+artifacts.primary.image>
  imagePullPolicy: Always

service:
  http:
    externalPort: 80
    internalPort: 8777
  jolokia:
    internalPort: 8778
rbac:
  enabled: false
ingress:
  name: stop-places-v1-gcp2


secrets:
  tiamat-psql-credentials:
    - SPRING_DATASOURCE_PASSWORD