minReplicas: 1
maxReplicas: 2
image: eu.gcr.io/carbon-1287/tiamat
imageTag: latest
imagePullPolicy: Always
slack: talk-ror
team: ror
type: backend
app: tiamat-nordic
api: nordic-stopplaces-register-v1
service:
  name: tiamat-nordic
  type: ClusterIP
  externalPort: 80
  internalPort: 8080
  internalJolokiaPort: 8778
  debugPort: 5005
resources:
  cpuLimit: "2"
  memLimit: 2048Mi
  cpuRequest: 200m
  memRequest: 512Mi
  xmx: 1024m

# Environment Specific
externalDns:
  ingressLoadBalancerIP:
    dev: "35.195.223.29"
    staging: "35.195.146.93"
    production: "35.187.15.14"
