env: dev
gcp2:
  enabled: true
sql:
  instance: ent-tiamat-dev:europe-west1:tiamat-db-1=tcp:5432

configMap:
  blobstoreProjectId: ent-tiamat-dev
  pubsubProjectId: ent-tiamat-dev
  pubsbuTopicName: ror.tiamat.changelog
  gcsBucketName: ror-tiamat-gcp2-dev

auth0:
  ror:
    url: https://ror-entur-dev.eu.auth0.com
    audience: https://ror.api.dev.entur.io

rbac:
  enabled: true

ingress:
  enabled: true
  domainName: .dev.entur.io