replicas: 2

sql:
  instance: radon-1287:europe-west1:tiamat-db-1=tcp:5432

configMap:
  blobstoreProjectId: entur-ror-test
  pubsubProjectId: entur-ror-test
  pubsbuTopicName: ror.tiamat.changelog
  gcsBucketName: tiamat-test
  keycloakUrl: https://kc-stage.devstage.entur.io/auth

rbac:
  enabled: true

ingress:
  enabled: true
  loadBalancerIP: 130.211.80.129
  domainName: .staging.entur.io