sql:
  instance: entur-ror-dev:europe-west1:tiamat-db-1-replica=tcp:5432

configMap:
  blobstoreProjectId: entur-ror-dev
  gcsBucketName: tiamat-exporter-dev
  keycloakUrl: https://kc-dev.devstage.entur.io/auth

auth0:
  ror:
    url: https://ror-entur-dev.eu.auth0.com
    audience: https://ror.api.dev.entur.io

rbac:
  enabled: true
