replicas: 2

sql:
  instance: neon-1287:europe-west1:tiamat-db-1=tcp:5432

configMap:
  blobstoreProjectId: neon-1287
  pubsubProjectId: entur-ror-prod
  pubsbuTopicName: ror.tiamat.changelog
  gcsBucketName: ror-tiamat-production
  keycloakUrl: https://auth.entur.org/auth

ingress:
  enabled: true
  loadBalancerIP: 35.187.15.14
  domainName: -production.entur.io