replicas: 2

sql:
  instance: radon-1287:europe-west1:tiamat-db-1=tcp:5432

configMap:
  blobstoreProjectId: radon-1287
  pubsubProjectId: entur-ror-test
  pubsbuTopicName: ror.tiamat.changelog
  gcsBucketName: ror-tiamat-test
  keycloakUrl: https://kc-stage.devstage.entur.io/auth


ingress:
  enabled: true
  loadBalancerIP: 35.195.146.93
  domainName: -staging.staging.entur.io