apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.deployment.name }}-config
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "common.labels" . | indent 4 }}
data:
  application.properties: |-
    server.port={{ .Values.service.http.internalPort }}
    peliasReverseLookupEndpoint=http://pelias.default/v1/reverse
    nearbyStopsWithSameTypeFinder.limits={railStation:'200',airport:'3000'}
    tariffzoneLookupService.resetReferences=true
    publicationDeliveryStreamingOutput.validateAgainstSchema=true
    publicationDeliveryUnmarshaller.validateAgainstSchema=true
    netex.import.enabled.types=MERGE
    changelog.publish.enabled=true
    spring.activemq.broker-url=tcp://activemq.default:61616?jms.redeliveryPolicy.maximumRedeliveries=0
    netex.id.valid.prefix.list={TopographicPlace:{'KVE','WOF','OSM','ENT','LAN'},TariffZone:{'*'},FareZone:{'*'}}

    # GCS properties
    blobstore.gcs.bucket.name={{.Values.configMap.gcsBucketName}}
    blobstore.gcs.blob.path=export
    blobstore.gcs.credential.path=/etc/tiamat/credentials.json
    blobstore.gcs.project.id={{.Values.configMap.blobstoreProjectId}}

    # Database properties
    spring.jpa.properties.javax.persistence.query.timeout=15000
    spring.jpa.properties.hibernate.dialect=org.hibernate.spatial.dialect.postgis.PostgisDialect
    spring.jpa.properties.hibernate.cache.region.factory_class=org.rutebanken.tiamat.hazelcast.TiamatHazelcastCacheRegionFactory
    spring.jpa.properties.hibernate.cache.use_second_level_cache=true
    spring.jpa.properties.hibernate.cache.use_minimal_puts=true
    spring.jpa.properties.hibernate.cache.use_query_cache=true
    spring.jpa.hibernate.ddl-auto=none
    spring.jpa.hibernate.use-new-id-generator-mappings=true
    spring.jpa.open-in-view=false
    spring.jpa.database=POSTGRESQL
    spring.jpa.show-sql=false
    spring.database.driverClassName=org.postgresql.Driver
    spring.datasource.hikari.maximumPoolSize=30
    spring.datasource.url=jdbc:postgresql://localhost:5432/{{ .Values.deployment.name }}
    spring.datasource.username=tiamat
    spring.datasource.platform=postgres

    # Keycloak Properties
    authorization.enabled=true
    keycloak.realm=rutebanken
    keycloak.auth-server-url={{.Values.configMap.keycloakUrl}}
    keycloak.principal-attribute=preferred_username
    keycloak.resource=Tiamat
    # Temporary setting until bug in KeycloakWebSecurityConfigurerAdapter is fixed (The bean ''httpSessionManager'', defined in class path resource XXXSecurityConfiguration.class],could not be registered. A bean with that name has already been defined in URL)
    spring.main.allow-bean-definition-overriding=true

    # Logging Properties
    logging.level.org.rutebanken.tiamat=INFO
    logging.level.org.rutebanken.tiamat.repository=DEBUG
    logging.level.org.rutebanken.tiamat.importer.finder=INFO
    logging.level.org.rutebanken.tiamat.dtoassembling.disassembler.StopPlaceSearchDisassembler=WARN
    logging.level.org.rutebanken.tiamat.rest.netex.publicationdelivery.PublicationDeliveryUnmarshaller=INFO
    logging.level.org.rutebanken.tiamat.rest.netex.publicationdelivery=INFO
    logging.level.org.rutebanken.tiamat.rest.netex.publicationdelivery.PublicationDeliveryStreamingOutput=INFO
    logging.level.org.springframework.orm.hibernate4.support=WARN
    logging.level.org.hibernate.SQL=WARN
    logging.level.org.hibernate.tool.hbm2ddl=INFO
    logging.level.org.hibernate.type=WARN
    logging.level.org.hibernate.id.enhanced=INFO

    #Profile
    spring.profiles.active=gcs-blobstore,google-pubsub

    # pubsub
    spring.cloud.gcp.project-id={{ .Values.configMap.pubsubProjectId }}
    spring.cloud.gcp.credentials.location=file:/etc/tiamat/credentials.json
    changelog.topic.name={{ .Values.configMap.pubsbuTopicName }}

