apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    {{- include "common.labels" . | indent 4 }}
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  progressDeadlineSeconds: 600
  replicas: {{ .Values.minReplicas }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      {{- include "common.labels" . | indent 8 }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        {{- include "common.labels" . | indent 8 }}
    spec:
      containers:
        - command:
            - /cloud_sql_proxy
            - -instances=carbon-1287:europe-west1:tiamat-nordic-db-1=tcp:5432
            - -credential_file=/secrets/cloudsql/credentials.json
          image: gcr.io/cloudsql-docker/gce-proxy:1.14
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - sleep 28
          name: cloudsql-proxy
          resources:
            requests:
              cpu: 50m
              memory: 40Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /secrets/cloudsql
              name: cloudsql-instance-credentials
        - command:
            - /deployments/run-java.sh
          env:
            - name: TZ
              value: Europe/Oslo
            - name: JAVA_OPTIONS
              value: -Xss{{ .Values.resources.ss }} -XX:+PrintGCDetails -XX:+PrintFlagsFinal -server -Dspring.config.location=/etc/application-config/application.properties
                -Xmx{{ .Values.resources.xmx }} -Dfile.encoding=UTF-8  -Drutebanken.kubernetes.namespace={{ .Release.Namespace }} -Drutebanken.kubernetes.enabled=true -Drutebanken.hazelcast.management.url=http://tiamat-hzmgmt/mancenter/
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: tiamat-nordic-db-password
          image: {{ .Values.image }}:{{ .Values.imageTag }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: health/live
              port: {{ .Values.service.internalPort }}
              scheme: HTTP
            initialDelaySeconds: 120
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 30
          name: {{ .Chart.Name }}
          ports:
            - containerPort: {{ .Values.service.internalPort }}
              name: http
              protocol: TCP
            - containerPort: {{ .Values.service.internalJolokiaPort}}
              name: jolokia
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: health/ready
              port: {{ .Values.service.internalPort }}
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 20
          resources:
            limits:
              cpu: {{ .Values.resources.cpuLimit }}
              memory: {{ .Values.resources.memLimit }}
            requests:
              cpu: {{ .Values.resources.cpuRequest }}
              memory: {{ .Values.resources.memRequest }}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /etc/tiamat
              name: tiamat-nordic-key
            - mountPath: /etc/application-config
              name: {{ .Values.app }}
              readOnly: true
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: rutebanken-registry-key
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 31
      volumes:
        - name: tiamat-dk-key
          secret:
            defaultMode: 420
            secretName: tiamat-dk-carbon-storage-key
        - name: cloudsql-instance-credentials
          secret:
            defaultMode: 420
            secretName: cloudsql-tiamat-dk-db-credentials
        - configMap:
            defaultMode: 420
            name: {{ .Values.app }}
          name: {{ .Values.app }}