apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels" . | indent 4 }}
spec:
  progressDeadlineSeconds: 600
  replicas: {{ .Values.replicas | default 3}}
  selector:
    matchLabels:
      app: {{ .Values.deployment.name }}
  strategy:
    rollingUpdate:
      maxSurge: {{ .Values.rollingUpdate.maxSurge }}
      maxUnavailable: {{ .Values.rollingUpdate.maxUnavailable }}
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus.io/path: /health/scrape
        prometheus.io/port: {{ .Values.service.http.internalPort }}
        prometheus.io/scrape: 'true'
      labels:
        {{- include "common.labels" . | indent 8 }}
    spec:
      containers:
        - name: cloudsql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.17
          imagePullPolicy: IfNotPresent
          command:
                - /cloud_sql_proxy
                - -instances={{ .Values.sql.instance }}
                - -credential_file=/etc/tiamat/credentials.json
                - -log_debug_stdout
          resources:
            requests:
              cpu: 50m
              memory: 40Mi
          volumeMounts:
            - mountPath: /etc/tiamat
              name: {{ .Values.secretMount.name }}
          lifecycle:
            preStop:
              exec:
                command:
                - /bin/sh
                - -c
                - sleep 28
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        - name: {{ .Values.deployment.name }}
          image: {{ .Values.image.identifier }}
          imagePullPolicy: {{ .Values.image.imagePullPolicy }}
          env:
            - name: JAVA_OPTIONS
              value: -server -Xss{{ .Values.resources.xss }} -Xmx{{ .Values.resources.xmx }} -Dspring.config.location=/etc/application-config/application.properties
                     -Dfile.encoding=UTF-8 -Drutebanken.kubernetes.enabled=true -Drutebanken.hazelcast.management.url=http://tiamat-hzmgmt/mancenter/
                     -Drutebanken.kubernetes.namespace={{ .Release.Namespace }}
            - name: TZ
              value: Europe/Oslo
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: ror-{{ .Values.deployment.name }}-db-password
          resources:
            limits:
              cpu: {{ .Values.resources.cpuLimit }}
              memory: {{ .Values.resources.memLimit }}
            requests:
              cpu: {{ .Values.resources.cpuRequest }}
              memory: {{ .Values.resources.memRequest }}
          volumeMounts:
            - name: {{ .Values.secretMount.name }}
              mountPath: {{ .Values.secretMount.mountPath }}
              subPath: {{ .Values.secretMount.subPath }}
              readOnly: {{ .Values.secretMount.readOnly }}
            - mountPath: /etc/application-config
              name: application-config
              readOnly: true
          ports:
            - containerPort: {{ .Values.service.http.internalPort }}
              name: http
              protocol: TCP
            - containerPort: {{ .Values.service.jolokia.internalPort }}
              name: jolokia
              protocol: TCP
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /health/live
              port: {{ .Values.service.http.internalPort }}
              scheme: HTTP
            initialDelaySeconds: 120
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 30
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /health/ready
              port: {{ .Values.service.http.internalPort }}
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 20
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: {{ .Values.deployment.name }}-service-account
      serviceAccountName: {{ .Values.deployment.name }}-service-account
      terminationGracePeriodSeconds: 31
      volumes:
        - name: {{ .Values.secretMount.name }}
          secret:
            secretName: {{ .Values.secretMount.secretName }}
        - name: application-config
          configMap:
            name: {{ .Values.configMapMount.name }}
            defaultMode: 420

