{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    {{- include "common.labels" . | indent 4 }}
    traffic-type: api
  annotations:
    kubernetes.io/ingress.class: traefik
  name: {{ .Values.ingress.name }}
  namespace: {{ .Release.Namespace }}
spec:
  rules:
  - host: {{ .Values.ingress.name }}{{ .Values.ingress.domainName }}
    http:
      paths:
        - pathType: ImplementationSpecific
          backend:
            service:
              name: {{ .Values.deployment.name }}
              port:
                number: {{ .Values.service.http.externalPort }}
{{- end }}
