{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  labels:
    {{- include "common.labels" . | indent 4 }}
  annotations:
    kubernetes.io/ingress.class: traefik
    external-dns.alpha.kubernetes.io/target: {{ .Values.ingress.loadBalancerIP }}
  name: {{ .Values.ingress.name }}
  namespace: {{ .Release.Namespace }}
spec:
  rules:
  - host: {{ .Values.ingress.name }}{{ .Values.ingress.domainName }}
    http:
      paths:
        - backend:
            serviceName: {{ .Values.deployment.name }}
            servicePort: {{ .Values.service.http.externalPort }}
{{- end }}
