DROP VIEW IF EXISTS place_equipment;

CREATE VIEW place_equipment AS

SELECT ievs.dtype,
       ievs.id,
       ievs.netex_id,
       ievs.changed,
       ievs.created,
       ievs.from_date,
       ievs.to_date,
       ievs.version,
       ievs.version_comment,
       ievs.out_of_service,
       ievs.private_code_type,
       ievs.private_code_value,
       ievs.number_of_machines,
       ievs.ticket_machines,
       ievs.ticket_office,
       ievs.cycle_storage_type,
       ievs.number_of_spaces,
       ievs.gender,
       ievs.number_of_toilets,
       ievs.brand_graphic,
       ievs.height,
       ievs.height_from_floor,
       ievs.machine_readable,
       ievs.sign_graphic,
       ievs.width,
       ievs.content_lang,
       ievs.content_value,
       ievs.sign_content_type,
       ievs.air_conditioned,
       ievs.heated,
       ievs.length,
       ievs.seats,
       ievs.smoking_allowed,
       ievs.step_free,
       ievs.wheelchair_area_length,
       ievs.wheelchair_area_width,
       ievs.enclosed,
       ievs.class_of_use_ref,
       ievs.women_only,
       ievs.changed_by,
       ievs.number_of_frames,
       ievs.line_signage,
       ievs.replaces_rail_sign,
       ievs.main_line_sign,
       ievs.note_value,
       ievs.note_lang,
       ievs.shelter_type,
       ievs.shelter_electricity,
       ievs.shelter_lighting,
       ievs.shelter_condition,
       ievs.timetable_cabinets,
       ievs.trash_can,
       ievs.shelter_has_display,
       ievs.bicycle_parking,
       ievs.leaning_rail,
       ievs.outside_bench,
       ievs.shelter_fascia_board_taping,
       ievs.shelter_number,
       ievs.shelter_external_id,
       ievsie.place_equipment_id as place_equipment_id

FROM installed_equipment_version_structure_installed_equipment AS ievsie

    INNER JOIN installed_equipment_version_structure ievs on ievsie.installed_equipment_id = ievs.id

ORDER BY netex_id ASC, version DESC;
